/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/macula-io/macula-php/cabi */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "content.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "directdial.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 26 "main.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "pubsub.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "rpc.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "serve.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "stream.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "ucan.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int macula_content_put(uintptr_t sessionHandle, unsigned char* data, int dataLen, char* name, uintptr_t identityHandle, unsigned char* mcidOut, char** errOut);
extern uintptr_t macula_content_get(uintptr_t sessionHandle, unsigned char* mcid34, uintptr_t identityHandle, char** errOut);
extern int macula_bytes_handle_len(uintptr_t bytesHandle);
extern void macula_bytes_handle_read(uintptr_t bytesHandle, unsigned char* out);
extern void macula_bytes_handle_free(uintptr_t bytesHandle);
extern char* macula_resolve_direct(uintptr_t sessionHandle, char* procedure, unsigned char* realm32, uintptr_t identityHandle, unsigned char* stationOut, uint16_t* portOut, char** errOut);
extern char* macula_resolve_direct_with_cert_chain(uintptr_t sessionHandle, char* procedure, unsigned char* realm32, unsigned char* realmCAPEM, int realmCAPEMLen, char* expectedOrg, uintptr_t identityHandle, unsigned char* stationOut, uint16_t* portOut, char** errOut);
extern uintptr_t macula_call_direct(uintptr_t resolveViaSessionHandle, char* procedure, unsigned char* realm32, int payloadKind, long long int payloadInt, unsigned char* payloadBytes, int payloadBytesLen, double payloadFloat, int timeoutMs, uintptr_t identityHandle, char** errOut);
extern uintptr_t macula_call_direct_with_cert_chain(uintptr_t resolveViaSessionHandle, char* procedure, unsigned char* realm32, unsigned char* realmCAPEM, int realmCAPEMLen, char* expectedOrg, int payloadKind, long long int payloadInt, unsigned char* payloadBytes, int payloadBytesLen, double payloadFloat, int timeoutMs, uintptr_t identityHandle, char** errOut);
extern uintptr_t macula_call_direct_with_ucan(uintptr_t resolveViaSessionHandle, char* procedure, unsigned char* realm32, int payloadKind, long long int payloadInt, unsigned char* payloadBytes, int payloadBytesLen, double payloadFloat, int timeoutMs, uintptr_t identityHandle, unsigned char* ucanToken, int ucanTokenLen, char** errOut);
extern void macula_advertise_direct(uintptr_t sessionHandle, char* procedure, unsigned char* realm32, long long int ttlMs, uintptr_t identityHandle, char** errOut);
extern void macula_advertise_direct_with_cert_chain(uintptr_t sessionHandle, char* procedure, unsigned char* realm32, long long int ttlMs, unsigned char* certChainPEM, int certChainPEMLen, uintptr_t identityHandle, char** errOut);
extern uintptr_t macula_stream_open_direct(uintptr_t resolveViaSessionHandle, char* procedure, unsigned char* realm32, int mode, int argsKind, long long int argsInt, unsigned char* argsBytes, int argsBytesLen, double argsFloat, long long int deadlineMs, int timeoutMs, uintptr_t identityHandle, uintptr_t* sessionHandleOut, char** errOut);
extern uintptr_t macula_stream_open_direct_with_cert_chain(uintptr_t resolveViaSessionHandle, char* procedure, unsigned char* realm32, unsigned char* realmCAPEM, int realmCAPEMLen, char* expectedOrg, int mode, int argsKind, long long int argsInt, unsigned char* argsBytes, int argsBytesLen, double argsFloat, long long int deadlineMs, int timeoutMs, uintptr_t identityHandle, uintptr_t* sessionHandleOut, char** errOut);
extern int macula_put_direct(uintptr_t resolveViaSessionHandle, unsigned char* station32, unsigned char* data, int dataLen, char* name, int timeoutMs, uintptr_t identityHandle, unsigned char* mcidOut, char** errOut);
extern uintptr_t macula_get_direct(uintptr_t resolveViaSessionHandle, unsigned char* mcid34, int timeoutMs, uintptr_t identityHandle, char** errOut);
extern void macula_free_string(char* s);
extern uintptr_t macula_identity_generate(char** errOut);
extern int macula_identity_node_id(uintptr_t identityHandle, unsigned char* out32);
extern uintptr_t macula_identity_from_seed_bytes(unsigned char* seed32, char** errOut);
extern int macula_identity_private_bytes(uintptr_t identityHandle, unsigned char* out32);
extern void macula_identity_free(uintptr_t identityHandle);
extern uintptr_t macula_connect(char* host, uint16_t port, uintptr_t identityHandle, int timeoutMs, char** errOut);
extern uintptr_t macula_connect_seeds(char* seedsCSV, uintptr_t identityHandle, int timeoutMs, char** errOut);
extern int macula_session_accepted(uintptr_t sessionHandle);
extern int macula_session_station_node_id(uintptr_t sessionHandle, unsigned char* out32);
extern void macula_session_close(uintptr_t sessionHandle, uintptr_t identityHandle);
extern void macula_publish(uintptr_t sessionHandle, char* topic, unsigned char* realm32, long long unsigned int seq, int payloadKind, long long int payloadInt, unsigned char* payloadBytes, int payloadBytesLen, double payloadFloat, long long int publishedAtMs, uintptr_t identityHandle, char** errOut);
extern void macula_subscribe(uintptr_t sessionHandle, char* topic, unsigned char* realm32, uintptr_t identityHandle, char** errOut);
extern void macula_unsubscribe(uintptr_t sessionHandle, char* topic, unsigned char* realm32, uintptr_t identityHandle, char** errOut);
extern void macula_advertise(uintptr_t sessionHandle, char* procedure, unsigned char* realm32, uintptr_t identityHandle, char** errOut);
extern void macula_unadvertise(uintptr_t sessionHandle, char* procedure, unsigned char* realm32, uintptr_t identityHandle, char** errOut);
extern uintptr_t macula_recv_event(uintptr_t sessionHandle, int timeoutMs, char** errOut);
extern char* macula_event_topic(uintptr_t eventHandle);
extern void macula_event_realm(uintptr_t eventHandle, unsigned char* out32);
extern void macula_event_publisher(uintptr_t eventHandle, unsigned char* out32);
extern long long unsigned int macula_event_seq(uintptr_t eventHandle);
extern char* macula_event_delivered_via(uintptr_t eventHandle);
extern int macula_event_payload_kind(uintptr_t eventHandle);
extern long long int macula_event_payload_int(uintptr_t eventHandle);
extern double macula_event_payload_float(uintptr_t eventHandle);
extern int macula_event_payload_bytes_len(uintptr_t eventHandle);
extern void macula_event_payload_bytes(uintptr_t eventHandle, unsigned char* out);
extern void macula_event_free(uintptr_t eventHandle);
extern uintptr_t macula_call(uintptr_t sessionHandle, char* procedure, unsigned char* realm32, int payloadKind, long long int payloadInt, unsigned char* payloadBytes, int payloadBytesLen, double payloadFloat, int timeoutMs, uintptr_t identityHandle, char** errOut);
extern int macula_response_is_error(uintptr_t responseHandle);
extern int macula_response_result_kind(uintptr_t responseHandle);
extern long long int macula_response_result_int(uintptr_t responseHandle);
extern double macula_response_result_float(uintptr_t responseHandle);
extern int macula_response_result_bytes_len(uintptr_t responseHandle);
extern void macula_response_result_bytes(uintptr_t responseHandle, unsigned char* out);
extern void macula_response_responded_by(uintptr_t responseHandle, unsigned char* out32);
extern int macula_response_error_code(uintptr_t responseHandle);
extern char* macula_response_error_name(uintptr_t responseHandle);
extern void macula_response_reported_by(uintptr_t responseHandle, unsigned char* out32);
extern char* macula_response_error_detail(uintptr_t responseHandle);
extern void macula_response_free(uintptr_t responseHandle);
extern uintptr_t macula_serve_wait_for_call(uintptr_t sessionHandle, uintptr_t identityHandle, int timeoutMs, char** errOut);
extern char* macula_pending_call_procedure(uintptr_t pendingHandle);
extern void macula_pending_call_realm(uintptr_t pendingHandle, unsigned char* out32);
extern int macula_pending_call_payload_kind(uintptr_t pendingHandle);
extern long long int macula_pending_call_payload_int(uintptr_t pendingHandle);
extern double macula_pending_call_payload_float(uintptr_t pendingHandle);
extern int macula_pending_call_payload_bytes_len(uintptr_t pendingHandle);
extern void macula_pending_call_payload_bytes(uintptr_t pendingHandle, unsigned char* out);
extern void macula_pending_call_reply_result(uintptr_t pendingHandle, int kind, long long int intVal, unsigned char* bytesVal, int bytesLen, double floatVal, char** errOut);
extern void macula_pending_call_reply_error(uintptr_t pendingHandle, char* detail, char** errOut);
extern void macula_pending_call_free(uintptr_t pendingHandle);
extern uintptr_t macula_stream_open(uintptr_t sessionHandle, char* procedure, unsigned char* realm32, int mode, int argsKind, long long int argsInt, unsigned char* argsBytes, int argsBytesLen, double argsFloat, long long int deadlineMs, uintptr_t identityHandle, char** errOut);
extern uintptr_t macula_stream_accept(uintptr_t sessionHandle, int timeoutMs, uintptr_t* openInfoHandleOut, char** errOut);
extern char* macula_stream_open_info_procedure(uintptr_t infoHandle);
extern void macula_stream_open_info_realm(uintptr_t infoHandle, unsigned char* out32);
extern int macula_stream_open_info_mode(uintptr_t infoHandle);
extern int macula_stream_open_info_args_kind(uintptr_t infoHandle);
extern long long int macula_stream_open_info_args_int(uintptr_t infoHandle);
extern double macula_stream_open_info_args_float(uintptr_t infoHandle);
extern int macula_stream_open_info_args_bytes_len(uintptr_t infoHandle);
extern void macula_stream_open_info_args_bytes(uintptr_t infoHandle, unsigned char* out);
extern long long int macula_stream_open_info_deadline_ms(uintptr_t infoHandle);
extern void macula_stream_open_info_caller(uintptr_t infoHandle, unsigned char* out32);
extern void macula_stream_open_info_free(uintptr_t infoHandle);
extern void macula_stream_send_data(uintptr_t streamHandle, int encoding, int bodyKind, long long int bodyInt, unsigned char* bodyBytes, int bodyBytesLen, double bodyFloat, uintptr_t identityHandle, char** errOut);
extern void macula_stream_close_send(uintptr_t streamHandle, uintptr_t identityHandle, char** errOut);
extern void macula_stream_send_reply(uintptr_t streamHandle, int payloadKind, long long int payloadInt, unsigned char* payloadBytes, int payloadBytesLen, double payloadFloat, uintptr_t identityHandle, char** errOut);
extern uintptr_t macula_stream_recv(uintptr_t streamHandle, int timeoutMs, char** errOut);
extern int macula_stream_item_is_eof(uintptr_t itemHandle);
extern long long unsigned int macula_stream_item_seq(uintptr_t itemHandle);
extern int macula_stream_item_encoding(uintptr_t itemHandle);
extern int macula_stream_item_body_kind(uintptr_t itemHandle);
extern long long int macula_stream_item_body_int(uintptr_t itemHandle);
extern double macula_stream_item_body_float(uintptr_t itemHandle);
extern int macula_stream_item_body_bytes_len(uintptr_t itemHandle);
extern void macula_stream_item_body_bytes(uintptr_t itemHandle, unsigned char* out);
extern void macula_stream_item_free(uintptr_t itemHandle);
extern uintptr_t macula_stream_await_reply(uintptr_t streamHandle, int timeoutMs, char** errOut);
extern int macula_stream_reply_kind(uintptr_t replyHandle);
extern long long int macula_stream_reply_int(uintptr_t replyHandle);
extern double macula_stream_reply_float(uintptr_t replyHandle);
extern int macula_stream_reply_bytes_len(uintptr_t replyHandle);
extern void macula_stream_reply_bytes(uintptr_t replyHandle, unsigned char* out);
extern void macula_stream_reply_responded_by(uintptr_t replyHandle, unsigned char* out32);
extern void macula_stream_reply_free(uintptr_t replyHandle);
extern void macula_stream_abort(uintptr_t streamHandle, char* code, char* message, uintptr_t identityHandle);
extern void macula_stream_free(uintptr_t streamHandle);
extern uintptr_t macula_ucan_create(char* issuer, char* audience, char* capabilitiesJSON, int hasExpiresAt, long long int expiresAtUnixSec, int hasNotBefore, long long int notBeforeUnixSec, uintptr_t identityHandle, char** errOut);
extern uintptr_t macula_ucan_verify(unsigned char* tokenBytes, int tokenLen, unsigned char* publicKey32, char** errOut);
extern uintptr_t macula_ucan_decode(unsigned char* tokenBytes, int tokenLen, char** errOut);
extern int macula_ucan_is_expired(unsigned char* tokenBytes, int tokenLen, char** errOut);
extern char* macula_ucan_payload_issuer(uintptr_t payloadHandle);
extern char* macula_ucan_payload_audience(uintptr_t payloadHandle);
extern long long int macula_ucan_payload_expires_at(uintptr_t payloadHandle, int* hasOut);
extern long long int macula_ucan_payload_not_before(uintptr_t payloadHandle, int* hasOut);
extern char* macula_ucan_payload_capabilities_json(uintptr_t payloadHandle);
extern char* macula_ucan_payload_proofs_json(uintptr_t payloadHandle);
extern void macula_ucan_payload_free(uintptr_t payloadHandle);
extern uintptr_t macula_call_with_ucan(uintptr_t sessionHandle, char* procedure, unsigned char* realm32, int payloadKind, long long int payloadInt, unsigned char* payloadBytes, int payloadBytesLen, double payloadFloat, int timeoutMs, uintptr_t identityHandle, unsigned char* ucanToken, int ucanTokenLen, char** errOut);
extern uintptr_t macula_serve_wait_for_call_gated(uintptr_t sessionHandle, uintptr_t identityHandle, int timeoutMs, unsigned char* requiredIssuer32, char** errOut);

#ifdef __cplusplus
}
#endif
